### DISCUSSION TITLE
Problems with Robotmk and CRE

### DISCUSSION THREAD

**Discussion by m3rlinux** [elabit/robotmk#182] [Q&A] [answered]
Hi,
I'm trying to configure my first test but unfortunately no "Service Discovery" is found.
I installed the software on CRE 2.0 following the courses: https://www.robotmk.org/collections

- Install Robotmk on Checkmk
- Prepare Windows as a Robotmk Client

I copied the plugin (robotmk.py) in folder "plugins" of monitored host, then I created robotmk.yml in "config" folder with this content:
```
# Created by Check_MK Agent Bakery.
# This file is managed via WATO, do not edit manually or you
# lose your changes next time when you update the agent.

global:
   agent_output_encoding: utf_8
   cache_time: 120
   execution_mode: cmk_async
   log_rotation: '14'
   robotdir: C:\ProgramData\checkmk\agent\robot
   robotframework:
      console: ''
      log: ''
      report: ''
suites:
   selenium_test: {}
#      variable:
#         TOOL1: RobotFramework
#         TOOL2: RobotMK
   test1: {}
```

and at the end I copied the folder containing the selenium test (selenium_test & test1) in the folder "C:\ProgramData\checkmk\agent\robot"; These test are in your repo: https://github.com/simonmeggle/robotmk-quickstart-windows 

Al seems to work as I saw in the log "check_mk.log":
```
2021-12-16 10:31:00.041 [srv 10476] perf:  In [2478] milliseconds process 'python.exe "C:\ProgramData\checkmk\agent\plugins\robotmk.py"' pid:[11672] SUCCEDED - generated [0] bytes of data in [0] blocks
2021-12-16 10:31:00.041 [srv 10476] [Warn ] Process 'C:\ProgramData\checkmk\agent\plugins\robotmk.py' has no data
```

and robotmk_controller.log:
```
2021-12-16 10:37:17,967    RMKCtrl [12348]    INFO: ====================
2021-12-16 10:37:17,967    RMKCtrl [12348]    INFO: Reading suite statefiles and encoding data (utf_8)...
2021-12-16 10:37:17,967    RMKCtrl [12348]    INFO: 2 Suites to check: selenium_test, test1
```

However in the agent the session `<<<robotmk>>>` is missing.

What can I do to for more debugging?

Sorry for my poor english.

Thanks!
