### ISSUE TITLE
Add RCC execution mode

### ISSUE THREAD

**Issue by simonmeggle** [elabit/robotmk#148]
Add a new suite execution mode "RCC" for agent plugins which allows bootstrapping Python environments in a predictable and efficient way. 

See https://github.com/robocorp/rcc/blob/master/docs/environment-caching.md

This new feature has a prototype repository: https://github.com/simonmeggle/robotmk-rcc-prototype

A sub-option could be to upload a RCC Robot ZIP file into CMK/WATO which is then transferred with the bakery to the clinent. See #110 

The suites definition in robotmk.yaml could be expanded like this: 

* `python`: which Python interpreter to use 
  * `os`: use the Python interpreter installed in the OS
  * `rcc`: use a virtualenv bootstrapped by rcc
* `source`:  where to get the sources from 
  * `local`: expect in `robotdir`
  * `git`: pull from a git repository
* `path`: the directory name/repository URL

```
global:
  agent_output_encoding: zlib_codec
  cache_time: 960
  execution_interval: 900
  execution_mode: agent_serial
  log_rotation: '14'
  logging: true
  robotdir: /usr/lib/check_mk_agent/robot
  transmit_html: true
suites: 
  # ("legacy mode")
  webtest1:
    python: os
    source: local
    path: --directory--

  # either the robot files are copied by hand to the client or
  # they were uploaded in WATO as ZIP. The agent plugin checks if the ZIP needs to be extracted in robotdir 
  webtest2:
    python: rcc
    source: local
    path: --directory--

  webtest3:
    python: rcc
    source: git
    path: --repo-url--

  # Pull the Robot sources from Robocorp. Needs internet access and authentication token.
  # Unsure if this mode makes any sense at all. 
  webtest4:
    python: rcc
    source: robocorp
    path: --robot-name--
   
```
